# Generated by Django 4.2 on 2024-04-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
