# Generated by Django 4.2 on 2024-04-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0007_rename_created_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
