# Generated by Django 4.2 on 2024-05-02 07:00

from django.db import migrations
import randompinfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0013_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=randompinfield.fields.RandomPinField(length=8, null='True'),
            preserve_default='True',
        ),
    ]
