# Generated by Django 4.2 on 2024-05-02 07:01

from django.db import migrations
import randompinfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0014_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=randompinfield.fields.RandomPinField(length=8),
        ),
    ]
