# Generated by Django 4.2 on 2024-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0015_alter_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sipariş Durumları',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Siparişler'},
        ),
    ]
