# Generated by Django 4.2 on 2024-05-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0016_orderstatus_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(default=1, to='commerce_app.orderitem'),
        ),
    ]
