# Generated by Django 4.2 on 2024-05-02 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0017_alter_order_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce_app.orderstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(to='commerce_app.orderitem'),
        ),
    ]
