# Generated by Django 4.2 on 2024-05-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0018_order_status_alter_order_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce_app.cargo'),
        ),
    ]
