# Generated by Django 4.2 on 2024-05-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0019_order_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('person', models.CharField(max_length=250)),
                ('tel', models.CharField(max_length=20)),
                ('vno', models.IntegerField(blank=True, max_length=10, null=True)),
                ('vda', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='user/')),
                ('adress', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postcode', models.IntegerField(max_length=7)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
