# Generated by Django 4.2 on 2024-05-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0020_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
