# Generated by Django 4.2 on 2024-05-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0021_alter_profile_postcode_alter_profile_vno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
