# Generated by Django 4.2 on 2024-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0023_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
