# Generated by Django 4.2 on 2024-05-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0029_alter_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slider/')),
                ('link', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Poster',
            },
        ),
    ]
