# Generated by Django 4.2 on 2024-05-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0031_alter_product_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce_app.size'),
        ),
    ]
