# Generated by Django 4.2 on 2024-05-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0033_alter_slider_options_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
