# Generated by Django 4.2.13 on 2024-05-21 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0035_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='commerce_app.cargo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='commerce_app.orderstatus'),
        ),
    ]
